#!/bin/sh

test -d /Applications/Sublime\ Text\ 2.app/ && {
  test /usr/local/bin/subl && rm /usr/local/bin/subl
  mkdir -p /usr/local/bin/
  ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
  exit 0
}

test -d /Applications/Sublime\ Text.app/ && {
  test /usr/local/bin/subl && rm /usr/local/bin/subl
  mkdir -p /usr/local/bin/
  ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
  exit 0
}

exit 1